### PR TITLE
feat: add intelligence method

### PR DESCRIPTION
**Pull request by sadadw1**
feat: add intelligence method #368

### CODE REVIEW

**Review by wtt40122 — APPROVED** [review]
+LGTM

**Comment by goodjava** [comment]
I think this is a very good idea. Could you specifically tell us how to reduce the cost for people to troubleshoot problems through Hera? Also mention the systems this system depends on and the timing of its future release.

**Comment by sadadw1** [comment]
> I think this is a very good idea. Could you specifically tell us how to reduce the cost for people to troubleshoot problems through Hera? Also mention the systems this system depends on and the timing of its future release.

I believe that reducing costs is mainly reflected in two aspects:

+ Problem troubleshooting does not require people to understand specific business details, nor does it require experienced developers to carry it out.
+ When troubleshooting some complex traces, AI will definitely be faster than humans.

The main external dependency of this module is the AI large model, and all data given to the AI large model comes from ozhera.

At present, the intelligent functions are just a framework, and the specific implementation will be carried out from time to time, so please stay tuned.

**Comment by goodjava** [comment]
This project seems to have AI backend dependencies. Have you considered relying on open-source AI backends like Dify in the later stages? By the way, do you have any plans to open-source your AI backend?

**Comment by sadadw1** [comment]
1. Not relying on an AI backend is to make OzHera lighter, reducing the costs for users in terms of building, launching, running, debugging, and maintaining.
2. Internally at Xiaomi, we rely on a backend similar to Dify, called the M78 BOT platform.
3. This platform may be open-sourced in the future, and at that time, OzHera will also support the ability to rely on M78. I believe this will make OzHera's capabilities even stronger.

**Review by goodjava — APPROVED** [review]
+LGMT

**Pull request merged**
